// Plan comptable tunisien (SCE) — nomenclature vérifiée, source : Journal
// Officiel / Système Comptable des Entreprises. Account labels stay in the
// official French nomenclature (as taught and used in Tunisia); class titles
// are bilingual for the UI.
export const PLAN_COMPTABLE = [
  {
    id: '1',
    label: { fr: 'Classe 1 · Capitaux propres & passifs non courants', ar: 'الصنف 1 · رؤوس الأموال والخصوم غير الجارية' },
    accounts: [
      ['10', 'Capital'],
      ['101', 'Capital social'],
      ['11', 'Réserves et primes liées au capital'],
      ['12', 'Résultats reportés'],
      ['13', 'Résultat de l’exercice'],
      ['14', 'Autres capitaux propres'],
      ['15', 'Provisions pour risques et charges'],
      ['16', 'Emprunts et dettes assimilées'],
      ['18', 'Autres passifs non courants'],
    ],
  },
  {
    id: '2',
    label: { fr: 'Classe 2 · Actifs non courants', ar: 'الصنف 2 · الأصول غير الجارية' },
    accounts: [
      ['21', 'Immobilisations incorporelles'],
      ['213', 'Logiciels'],
      ['214', 'Fonds commercial'],
      ['22', 'Immobilisations corporelles'],
      ['23', 'Immobilisations en cours'],
      ['25', 'Participations et créances liées'],
      ['26', 'Autres immobilisations financières'],
      ['28', 'Amortissements des immobilisations'],
      ['29', 'Provisions pour dépréciation des actifs immobilisés'],
    ],
  },
  {
    id: '3',
    label: { fr: 'Classe 3 · Stocks', ar: 'الصنف 3 · المخزونات' },
    accounts: [
      ['31', 'Matières premières et fournitures liées'],
      ['32', 'Autres approvisionnements'],
      ['33', 'En-cours de production de biens'],
      ['34', 'En-cours de production de services'],
      ['35', 'Stocks de produits'],
      ['37', 'Stocks de marchandises'],
      ['39', 'Provisions pour dépréciation des stocks'],
    ],
  },
  {
    id: '4',
    label: { fr: 'Classe 4 · Tiers (la plus utilisée)', ar: 'الصنف 4 · الغير (الأكثر استعمالا)' },
    accounts: [
      ['401', 'Fournisseurs d’exploitation'],
      ['404', 'Fournisseurs d’immobilisations'],
      ['408', 'Fournisseurs · factures non parvenues'],
      ['409', 'Fournisseurs débiteurs (avances versées)'],
      ['411', 'Clients'],
      ['413', 'Clients · effets à recevoir'],
      ['416', 'Clients douteux ou litigieux'],
      ['419', 'Clients créditeurs (avances reçues)'],
      ['42', 'Personnel et comptes rattachés'],
      ['425', 'Personnel · rémunérations dues'],
      ['43', 'État et collectivités publiques'],
      ['432', 'État · impôts et taxes retenus à la source'],
      ['4366', 'TVA déductible (sur achats)'],
      ['4367', 'TVA collectée (sur ventes)'],
      ['437', 'Organismes sociaux (CNSS)'],
      ['45', 'Débiteurs et créditeurs divers'],
      ['47', 'Comptes de régularisation'],
    ],
  },
  {
    id: '5',
    label: { fr: 'Classe 5 · Comptes financiers (trésorerie)', ar: 'الصنف 5 · الحسابات المالية (الخزينة)' },
    accounts: [
      ['50', 'Emprunts et dettes financières courants'],
      ['506', 'Concours bancaires courants'],
      ['52', 'Placements courants'],
      ['53', 'Banques et établissements financiers'],
      ['532', 'Banques'],
      ['54', 'Caisse'],
      ['55', 'Régies d’avances et accréditifs'],
      ['58', 'Virements internes'],
    ],
  },
  {
    id: '6',
    label: { fr: 'Classe 6 · Charges (chaque dépense)', ar: 'الصنف 6 · المصاريف (كل خرجة فلوس)' },
    accounts: [
      ['60', 'Achats'],
      ['607', 'Achats de marchandises'],
      ['603', 'Variation des stocks'],
      ['61', 'Services extérieurs (loyers, entretien...)'],
      ['62', 'Autres services extérieurs (honoraires, pub...)'],
      ['63', 'Charges diverses ordinaires'],
      ['64', 'Charges de personnel (salaires)'],
      ['65', 'Charges financières (intérêts, agios)'],
      ['66', 'Impôts, taxes et versements assimilés'],
      ['68', 'Dotations aux amortissements et provisions'],
      ['69', 'Impôts sur les bénéfices'],
    ],
  },
  {
    id: '7',
    label: { fr: 'Classe 7 · Produits (chaque vente)', ar: 'الصنف 7 · المداخيل (كل بيعة)' },
    accounts: [
      ['70', 'Ventes et prestations de services'],
      ['707', 'Ventes de marchandises'],
      ['706', 'Prestations de services'],
      ['71', 'Production stockée'],
      ['72', 'Production immobilisée'],
      ['73', 'Produits divers ordinaires'],
      ['74', 'Subventions d’exploitation'],
      ['75', 'Produits financiers'],
      ['78', 'Reprises sur amortissements et provisions'],
    ],
  },
];
